# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - aerospike
    environment:
      - AEROSPIKE_HOST=aerospike
    networks:
      - backend
    ports:
      - 8080:8080
    restart: unless-stopped
  
  aerospike:
    image: aerospike/aerospike-server
    networks:
      - backend
    ports:
      - 3000-3002:3000-3002
    volumes:
      - aerospike-data:/opt/aerospike/data
      - aerospike-config:/etc/aerospike
volumes:
  aerospike-data:
  aerospike-config:

networks:
  backend: